AWSTemplateFormatVersion: "2010-09-09"
Description: Simple S3 Bucket Stack

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-bucket"
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Value: !Ref MyS3Bucket
    Description: Name of the created S3 bucket
