name: Deploy Stack

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: "Choose AWS region"
        required: true
        default: "ap-south-1"
        type: choice
        options:
          - us-east-1
          - us-west-1
          - ap-south-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate region is in config
        run: |
          REGION="${{ github.event.inputs.aws_region }}"
          grep "$REGION" env/config.yml || (echo "Region $REGION not in config.yml" && exit 1)

      # Add your AWS deploy step here, using ${{ github.event.inputs.aws_region }}
