name: Environment Builder

on:
  workflow_dispatch:

jobs:
  build-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Assume you manually edit env/config.yml with the regions you want
      # If you want to automate this, let me know!

      - name: Commit env/config.yml
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add env/config.yml
          git commit -m "Update environment config"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
